### ISSUE TITLE
In Windows with 64 Bit and 32 Bit Tcl/Tk

### ISSUE THREAD

**Issue by gregnix** [aplsimple/alited#15]
When using alited under Windows 10
Tcl/Tk is installed as 64 bit in C:\Tcl.
The PATH of Windows contains: C:\Tcl\bin

There is also an installation of a 32 bit version 
of Tcl/Tk in C:\Tcl.32

If I change the PATH with C:\Tcl.32\bin and this within PATH
before C:\Tcl\bin, tclsh or wish is then called as 32 bit.
PATH change and the call tclsh/wish is made by starttcl32.cmd

Alited runs in 64 bit during normal startup.
If I have 32 bit projects, I call alited with starttcl32.cmd.
It works.

Can I somehow make this project-related in alited? 
That a certain Tcl/Tk version is used including customization of PATH. 
C:\Tcl.32\bin or also C:\Tcl.87-64, etc..

C:\PG\\alited\src\alited.tcl

starttcl32.cmd

```
@echo off
setlocal

set Scriptpath=%cd%\alited\src
set Tclscript=alited.tcl

set PATH=C:\Tcl.32\bin;%PATH%

set Tclprog=C:/Tcl.32/bin/wish.exe
set cmdtitle="Starter %Tclscript% in 32bit env"

start %cmdtitle% /d %Scriptpath%  %Tclprog% %Tclscript%

endlocal
exit

rem Explanation
rem/||(
starttcl32.cmd in C:\PG
C:\PG\starttcl32.cmd

set Tclprog=C:/Tcl.32/bin/wish.exe
start %cmdtitle% /d %Scriptpath%  %Tclprog% %Tclscript%
 or
set Tclprog=C:/Tcl.32/bin/tclsh.exe
start %cmdtitle% /min /d %Scriptpath%  %Tclprog% %Tclscript%

%cd%: Type cd without parameters to display the current drive and directory.

 PATH 
Set the entry C:\Tcl.32\bin at the beginning of the PATH
set PATH=C:\Tcl.32\bin;%PATH%

64bit install in C:\Tcl: C:\Tcl\bin
32bit install in C:\Tcl\bin: C:\Tcl.32\bin

setlocal: Starts limiting the scope of changes.
endlocal: Stops limiting the scope of changes.
start: Launches a separate Command Prompt window to run a specified program or command.
)  
```

Gregor

**Comment by aplsimple** [comment]
If I understand your problem properly, you want that alited could run some 32 bit projects with Tcl 32bit, while others - with Tcl 64bit (or alternatively with Tcl v8.6, Tcl v8.7 etc).

This is made with Tools/Run... dialogue. Its settings are per project, so that you can run (test) some projects with Tcl32, others with Tcl64. 

Moreover, any single project can be tested with both (or more) Tcl, if you set several commands in Tools/Run... dialogue, in separate lines of the text box - then just place the cursor on a required command.

The commands might be:

```
C:\Tcl.32\bin\tclsh.exe myproj1.tcl arg1 arg2...

C:\Tcl.64\wish.exe myproj2.tcl arg1 arg2...
```

If your Tcl executable command includes spaces (not pretty nice case though), then quote it, i.e.

`"C:\Tcl 64\wish.exe" myproj3.tcl arg1 arg2...`
__________

Side note. For Windows I should correct the Tcl executable's path after choosing it from the file picker of the Tools/Run dialogue (to use backslashes in the path). In nearest version.

**Comment by gregnix** [comment]
> ...
> This is made with Tools/Run... dialogue. Its settings are per project, so that you can run (test) some projects with Tcl32, others with Tcl64.
> 
Ok, I missed that. That should make it work. Thanks
