### ISSUE TITLE
directory with space in the name

### ISSUE THREAD

**Issue by gregnix** [aplsimple/alited#18]
Hello, 

directory with space in the name

Execution in alited with error:

```
/usr/bin/tclsh /home/greg/Project/2024/tcl/example/dir space/testa.tcl 


couldn't read file "/home/greg/Project/2024/tcl/example/dir": no such file or directory

Press return to continue

```

The error may have been going on for a long time.
Doesn't have to be the latest version.

alited v1.8.4 (10 May'24), a lite editor.
Linux 
Tcl/Tk 8.6..14

**Comment by aplsimple** [comment]
Yes, it's a birthmark of alited: it dislikes spaces in any file name. If possible, avoid them, otherwise some dances with quoting will be necessary.

In your case, try to use apostrophes (in Linux) or maybe escaped quotes (in Windows)

I.e. in Tools/Run dialogue, in the text box, set one of the following commands:
```
tclsh '%f'
tclsh \"%f\"
```
Then click "Save" button.

Here, %f is the wildcard for the current edited file. It should fit to _home/greg/Project/2024/tcl/example/dir space/testa.tcl_ and other .tcl files of **example** project.

**Comment by gregnix** [comment]
Ok, the easiest thing for me is to avoid the spaces
