### ISSUE TITLE
no ouput in consoke with alited

### ISSUE THREAD

**Issue by gregnix** [aplsimple/alited#19]
puts [package versions pdf4tcl]

If I run the command in alited in the console,
the version number does not appear.
package require pdf4tcl works.
If I use tkcon to run it, the version number is displayed.
Without Alited, the version number appears in the console.
The problem occurs for me with Alited on both Windows and Linux.
Gregor

**Comment by aplsimple** [comment]
Hi Gregor,

Thanks for the feedback.

It is my omission that this issue isn't described in the alited's docs. It's all about Preferences/Tools/tclsh option and Tools/Run dialogue.

In fact, it is not much of issue, moreover it is not specifically of alited.

But I should document it better. After the documenting I'll try to answer better too:)

-----

For the quick resolution, try to run alited with *tclsh* command, supposedly Tcl/Tk is installed in your platform, Windows or Linux.

**Comment by gregnix** [comment]
hello,
start alited with tcl
Exec=/usr/bin/env tclsh /home/greg/pg/share/alited/src/alited.tcl %F
or
tclsh ./pg/share/alited/src/alited.tcl
The problem is still there when I
Run in console
but not
Run in tkcon

the script:
```
#! /usr/bin/env tclsh

puts [info nameofexecutable]
puts [info patchlevel]
puts [package versions pdf4tcl]

puts a
```

Output:
/usr/bin/tclsh
8.6.14

a

will read the detailed documentation,
thanks for the alited program

**Comment by aplsimple** [comment]
Sorry, I understood your question wrongly. It's about *package versions
pdf4tcl*, not *puts* in general.

It seems that the *pdf4tcl* package is fetched inside *tkcon*,
in some initialization code, after that the *package versions pdf4tcl*
command shows pdf4tcl's version.

Running tclsh from the alited is as follows: if *Preferences/Tools/tclsh*
option is empty, then the tcltk kit to be run is the same kit that runs the
alited. Otherwise the option sets it directly.
If the alited was installed by its installer, then the tcltk kit running it
is in the *install-dir/alited/bin* directory.

Of course, this setting can be reset in *Tools/Run...* dialogue.

I should note that the alited installers till v1.8.4 have included the
*tcltk-8.6.10* binary (~30 Mb) containing the *pdf4tcl* package of 0.9.3
version, among others. Which is good, but redundant for alited.
Since v1.8.4 the alited installers include *wish8.7* binary plus *Img* and
*treectrl* packages (for the loupe tool) - which is much smaller (~6 Mb).
Consequently no libraries like *pdf4tcl*.

I would use the explicit commands to fetch the *pdf4tcl* and similar
external packages from subdirectories of your applications, not cherishing
hopes for their availability on the client machines.

E.g. this way

set ::auto_path [linsert $::auto_path 0 some-dir/pdf4tcl094]
> package require pdf4tcl
> puts "pdf4tcl versions: [package versions pdf4tcl]"
