### ISSUE TITLE
Display .gitignore in file browser

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#22]
Hello!
Could you please advise - how to show .gitignore file in file browser, as well as .git subfolder?
I tried to change it in options of the project, the option Skip subdirectories, but it didn't help.
Thank you in advance, George.

**Comment by par7133** [comment]
Alex, I'm really a bad mantainer.. but RADXIDE has an elaborated section
about hidden files in the scanning func of its tree.tcl:

https://github.com/par7133/RADXIDE/blob/main/tree.tcl

I hope you can find it *hintuitive* enough and helpful (ahah, I remember nothing of Tlc at time...)
;-)

-CC

Jul 8, 2024 16:28:02 Alex Plotnikov ***@***.***>:

**Comment by aplsimple** [comment]
Fixed in v1.8.6b2

---
Daniele, thanks for advice. As for RADXIDE project, is it suspended?

**Comment by par7133** [comment]
RADXIDE is much more simpler project then Alited, after some two-three important indipendent bug fixes code is actually is standby
but project is not suspended, RADXIDE remain a tool part of my dev environment indeed, actually working perfectly under Unix.

But I have to be sincer saying that I'm 90% of my time on web development and 10% for OpenBSD and as RADXIDE born from a subset of an old version of Alited code and doesnt follow up on Alited code (also because doesnt have tabs, system integration, etc)..it has its life, and as Alited is upgrading and bugfixing, as Tcl/tk is upgrading and bugfixing..although slowly these processes can happen I don't feel like the proper conditions to maintain RADXIDE.

Maybe for personal needs RADXIDE developmemt and maintenance could anyway happen but as one developer from its own
I can't garantee anything to RADXIDE users.

-CC

Jul 8, 2024 20:14:50 Alex Plotnikov ***@***.***>:

**Comment by georgtree** [comment]
> Fixed in v1.8.6b2
 Thanks a lot 😊
