### ISSUE TITLE
Issue with Ctrl+S 

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#34]
Hello!
I can't reproduce it with confidence, but sometimes combination of Ctrl+S becomes 'Save as...' instead of just Save, and it affects all files if it happens in current session. Button in menu 'Save' works as usual.
Regards, George.

**Comment by aplsimple** [comment]
Would you please look at Preferences/Keys settings?
---
In former days of alited, I had the settings as F2 for "Save" and Ctrl+S for "Save as" (and have so for my platform). Perhaps a wrong configuration is drawn from those days, in some of your platform. Then just redefine the settings.

**Comment by georgtree** [comment]
Just checked, settings are fine :(

**Comment by aplsimple** [comment]
Fixed in v1.8.7b5.

Before deploying it, you can reproduce the issue with the old v1.8.7b4.

The issue is reproduced after:
 - call Preferences and cancel it
 - switch to other project (or just switch to not-yet-viewed texts)

... then the _old default_ key bindings were applied to not-yet-viewed texts. (The _old defaults_ included F2 for "Save" and Ctrl+S for "Save as").

Thanks for the feedback.

**Comment by georgtree** [comment]
Thank you very much!
