### ISSUE TITLE
Issue with code autocomplete

### ISSUE THREAD

**Issue by georgtree** [aplsimple/alited#35]
Hello!
I have an issue with auto completion on Linux machine (not WSL). On Windows all works well, but on Linux
when I press tab, I only got some flickering near cursor but menu with suggestions not appears.
Thank you in advance, George.

**Comment by aplsimple** [comment]
Hi,

What's your Linux (OS, desktop manager)?

I've checked alited in Xfce, KDE, Gnome, Cinnamon, LXDE, LXQT, Openbox,  Fluxbox (all in Debian). In these environments, alited works fine.

**Comment by georgtree** [comment]
Hello, I use Kubuntu, so it is KDE

**Comment by aplsimple** [comment]
Would you please execute in tclsh the command:
```
expr {[info exists ::env(XDG_CURRENT_DESKTOP)] && $::env(XDG_CURRENT_DESKTOP) eq {KDE}}
```
and report the result?

**Comment by georgtree** [comment]
I found the source of issue: I switched back to default theme of kubuntu and all works fine there, but with theme from Kvantum manager it doesn't work when I switch back.

**Comment by georgtree** [comment]
Another update - it was not kvantum manager but particular theme: https://store.kde.org/p/2139482

**Comment by aplsimple** [comment]
I would play with alited's themes too (Preferences/General/Theme).

**Comment by aplsimple** [comment]
Well, I need your help with the following:
 - in *src/complete.tcl* of your alited source directory, please set the 247-th line as
`if {$w>20 && $h2>20} {`
 - restart alited to test it

Thanks in advance.

**Comment by georgtree** [comment]
Hello, I did it and issue is still not resolved. I can switch theme without restarting Alited and clearly see that with non-default theme auto-completion stops working. I recorded video in which I changed theme and problem appears, and then switch back and auto-completion works again:

Uploading 2024-08-24 18-36-37.mp4…

**Comment by aplsimple** [comment]
Hi George,

The problem is that I can't reproduce the issue.

See the attached video. (Supposedly, the Tools/Screen Loup of alited should fail too if the completion fails.)

However, I've modified complete.tcl (attached) and now I would ask you to test it, thanks in advance.

If the modification won't help, I don't know what to do with the issue. Supposedly close it?

---

All seems like the problem isn't of alited nor even of Tk, but of KDE specific themes that aren't fully correct.

Even reporting the issue to Tcl core team won't help, as no one will take it to fix. It's nearly 100%. The issue is too specific and seems to be originated from KDE theme inconsistencies.

They say in https://forum.manjaro.org/t/how-to-install-the-theme-manually/109117/2

_themes can cause system instabilities or weird issues when Plasma is updated. If you experience issues switch to the default Breeze theme (apply theme defaults) before reporting errors._

If I was you I would abstain from using non-default KDE themes at all, as I don't know if they are fully correct. Who knows where else the issues will occur with them?
[complete.zip](https://github.com/user-attachments/files/16739403/complete.zip)

https://github.com/user-attachments/assets/22f84df1-7d04-4075-b721-c9dc1c156560

**Comment by georgtree** [comment]
Hello, I tried new complete.tcl file, it didn't fix it but anyway you are right, who knows why this theme doesn't work well on my particular PC :)
I close the issue then!
Thank you :)

**Comment by aplsimple** [comment]
Looks weird. Is it the same _complete.tcl_ as attached above?
My _complete.tcl_ is 15820 bytes and doesn't contain the _traceList_ command.

**Comment by georgtree** [comment]
You're right, issue is fixed now, thank you!
But what was the cause of it?

**Comment by aplsimple** [comment]
The cause was in the following out-commented lines:

```
#!    frame $win
#!    wm manage $win
    toplevel $win
```

I took them without much thinking from alited 's screen loupe that in turn took them from the Tcl wiki.

 (The reason why I asked you to test the Tools/Screen loupe as well.)
